name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export Docker image (linux/amd64)
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: false
          outputs: type=docker,dest=/tmp/docker-image-amd64.tar
          tags: docker-ouc-portal:latest-amd64

      - name: Upload amd64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-amd64
          path: /tmp/docker-image-amd64.tar

      - name: Build and export Docker image (linux/arm64)
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/arm64
          push: false
          outputs: type=docker,dest=/tmp/docker-image-arm64.tar
          tags: docker-ouc-portal:latest-arm64

      - name: Upload arm64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-arm64
          path: /tmp/docker-image-arm64.tar
