name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image and export
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: docker-ouc-portal:latest # 为镜像指定名称和标签
          push: false
          outputs: type=docker,dest=/tmp/image.tar # 将镜像导出为 tar 文件到 /tmp/image.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: /tmp/image.tar # 上传导出的镜像文件作为构建产物
